version: '3'

services:
  frontend:
    build: .
    container_name: my-contacts-fe_c
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      REACT_APP_API_URL: http://10.1.1.2:3001
    stdin_open: true
    tty: true